name: Audit

on:
  pull_request:
    branches: [main]

jobs:
  CI:
    name: Audit
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2

    - name: Verify dependencies
      run: go mod verify

    - name: Run go vet
      run: go vet ./...

    - name: Run tests
      run: go test -race -vet=off ./...

    - name: Build
      run: go build -v .
