name: Audit

on:
  pull_request:
    branches: [main]

jobs:
  CI:
    name: Audit
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Verify dependencies
      run: go mod verify

    - name: Run go vet
      run: go vet ./...

    - name: Run tests
      run: go test -race -vet=off ./...

    - name: Build
      run: go build -v .
      
    - name: Install swaggo/swag
      run: go install github.com/swaggo/swag/cmd/swag@latest
    
    - name: Check for contract changes
      run: |
        swag init
        if [[ -n $(git diff) ]]; then
            echo Contract changes were made, run `swag init` before pushing
            exit 1
        else
            echo Contract is up to date with code
        fi

